# Site settings
title: Cindy Cheon
baseurl: ""
url: "https://cindy0306.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
    name: Cindy Cheon
    url: https://cindy0306.github.io
    email: cindy180306@gmail.com
    github: cindy0306
    twitter: cindy0306

# Build settings
markdown: kramdown
include:
    - _pages

# Assets
sass:
    sass_dir: _sass
    style: compressed

# Gems
plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-seo-tag
    # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

collections:
    dev:
        output: true
    book:
        output: true
    blog:
        output: true

# Disqus (Set to your disqus id)
disqus: jekyll-tale
